### ISSUE TITLE
run postprocess_onnx.py failed

### ISSUE THREAD

**Issue by maoxiaoming86** [NVIDIA/sampleQAT#2]
When I use postprocess_onnx to process the onnx model which is the output of step 4, encounter a erro:
Traceback (most recent call last):
  File "postprocess_onnx_ori.py", line 54, in <module>
    graph = process_transpose_nodes(graph)
  File "postprocess_onnx_ori.py", line 33, in process_transpose_nodes
    conv_weights_tensor = node.i(1).i().i().inputs[0]
  File "/root/.local/lib/python3.8/site-packages/onnx_graphsurgeon/ir/node.py", line 62, in i
    return self.inputs[tensor_idx].inputs[producer_idx]

Then I view the onnx model by Netron, I find that every conv node's input[1] is just a tensor, not a node, so when run node.i(1) failed. Is this a bug or miss some instructions between step 4 and step5?

**Comment by wilbur-caper** [comment]
How can this be solved?
